-- Seed: vendors.sql
-- Initial vendor data for pharmacies and supplement stores

INSERT INTO "Vendor" (id, name, website, "scraperFile") VALUES
    (gen_random_uuid()::text, '4Fitness', 'https://4fitness.rs', '4fitness.ts'),
    (gen_random_uuid()::text, 'Adonis', 'https://adonis.rs', 'adonis.ts'),
    (gen_random_uuid()::text, 'Alek Suplementi', 'https://aleksuplementi.rs', 'alekSuplementi.ts'),
    (gen_random_uuid()::text, 'Aleksandar MN', 'https://aleksandarmn.rs', 'aleksandarMn.ts'),
    (gen_random_uuid()::text, 'AMG Sport', 'https://amgsport.rs', 'amgSport.ts'),
    (gen_random_uuid()::text, 'Ananas', 'https://ananas.rs', 'ananas.ts'),
    (gen_random_uuid()::text, 'Apoteka Net', 'https://apoteka.net', 'apotekaNet.ts'),
    (gen_random_uuid()::text, 'Apoteka Niš', 'https://apotekanis.rs', 'apotekaNis.ts'),
    (gen_random_uuid()::text, 'Apoteka Online', 'https://apotekaonline.rs', 'apotekaOnline.ts'),
    (gen_random_uuid()::text, 'Apoteka Shop', 'https://apotekashop.rs', 'apotekaShop.ts'),
    (gen_random_uuid()::text, 'Apoteka Sunce', 'https://apotekasunce.rs', 'apotekaSunce.ts'),
    (gen_random_uuid()::text, 'Apoteka Valerijana', 'https://apotekavalerijana.rs', 'apotekaValerijana.ts'),
    (gen_random_uuid()::text, 'Apoteka Živanović', 'https://apotekazivanovic.rs', 'apotekaZivanovic.ts'),
    (gen_random_uuid()::text, 'Apotekamo', 'https://apotekamo.rs', 'apotekamo.ts'),
    (gen_random_uuid()::text, 'Apotekar Online', 'https://apotekaronline.rs', 'apotekarOnline.ts'),
    (gen_random_uuid()::text, 'Apothecary', 'https://apothecary.rs', 'apothecary.ts'),
    (gen_random_uuid()::text, 'ATP Sport', 'https://atpsport.rs', 'atpSport.ts'),
    (gen_random_uuid()::text, 'Azgard', 'https://azgard.rs', 'azgard.ts'),
    (gen_random_uuid()::text, 'Bazzar', 'https://bazzar.rs', 'bazzar.ts'),
    (gen_random_uuid()::text, 'Benu', 'https://benu.rs', 'benu.ts'),
    (gen_random_uuid()::text, 'Biofarm', 'https://biofarm.rs', 'biofarm.ts'),
    (gen_random_uuid()::text, 'DM', 'https://dm.rs', 'dm.ts'),
    (gen_random_uuid()::text, 'Dr.Max', 'https://drmax.rs', 'drMax.ts'),
    (gen_random_uuid()::text, 'eApoteka', 'https://eapoteka.rs', 'eApoteka.ts'),
    (gen_random_uuid()::text, 'eApoteka Net', 'https://eapoteka.net', 'eApotekaNet.ts'),
    (gen_random_uuid()::text, 'eApoteka RS', 'https://eapoteka.rs', 'eApotekaRs.ts'),
    (gen_random_uuid()::text, 'ePlaneta', 'https://eplaneta.rs', 'ePlaneta.ts'),
    (gen_random_uuid()::text, 'Esensa', 'https://esensa.rs', 'esensa.ts'),
    (gen_random_uuid()::text, 'ExYu Fitness', 'https://exyufitness.rs', 'exYuFitness.ts'),
    (gen_random_uuid()::text, 'Explode', 'https://explode.rs', 'explode.ts'),
    (gen_random_uuid()::text, 'Farmasi', 'https://farmasi.rs', 'farmasi.ts'),
    (gen_random_uuid()::text, 'Filly', 'https://filly.rs', 'filly.ts'),
    (gen_random_uuid()::text, 'FitLab', 'https://fitlab.rs', 'fitLab.ts'),
    (gen_random_uuid()::text, 'Fitness Shop', 'https://fitnessshop.rs', 'fitnessShop.ts'),
    (gen_random_uuid()::text, 'Flos', 'https://flos.rs', 'flos.ts'),
    (gen_random_uuid()::text, 'GymBeam', 'https://gymbeam.rs', 'gymBeam.ts'),
    (gen_random_uuid()::text, 'Herba', 'https://herba.rs', 'herba.ts'),
    (gen_random_uuid()::text, 'Hiper', 'https://hiper.rs', 'hiper.ts'),
    (gen_random_uuid()::text, 'House of Supplements', 'https://houseofsupplements.rs', 'houseOfSupplements.ts'),
    (gen_random_uuid()::text, 'Janković', 'https://jankovic.rs', 'jankovic.ts'),
    (gen_random_uuid()::text, 'Jugofarm', 'https://jugofarm.rs', 'jugofarm.ts'),
    (gen_random_uuid()::text, 'Krsenković', 'https://krsenkovic.rs', 'krsenkovic.ts'),
    (gen_random_uuid()::text, 'Lama', 'https://lama.rs', 'lama.ts'),
    (gen_random_uuid()::text, 'Laurus', 'https://laurus.rs', 'laurus.ts'),
    (gen_random_uuid()::text, 'Lily', 'https://lily.rs', 'lily.ts'),
    (gen_random_uuid()::text, 'Livada', 'https://livada.rs', 'livada.ts'),
    (gen_random_uuid()::text, 'Maelia', 'https://maelia.rs', 'maelia.ts'),
    (gen_random_uuid()::text, 'MaxFarm', 'https://maxfarm.rs', 'maxFarm.ts'),
    (gen_random_uuid()::text, 'Maximalium', 'https://maximalium.rs', 'maximalium.ts'),
    (gen_random_uuid()::text, 'MedX Apoteka', 'https://medxapoteka.rs', 'medXapoteka.ts'),
    (gen_random_uuid()::text, 'Melisa', 'https://melisa.rs', 'melisa.ts'),
    (gen_random_uuid()::text, 'Milica', 'https://milica.rs', 'milica.ts'),
    (gen_random_uuid()::text, 'Moć Bilja', 'https://mocbilja.rs', 'mocBilja.ts'),
    (gen_random_uuid()::text, 'Nature Hub', 'https://naturehub.rs', 'natureHub.ts'),
    (gen_random_uuid()::text, 'Oaza Zdravlja', 'https://oazazdravlja.rs', 'oazaZdravlja.ts'),
    (gen_random_uuid()::text, 'Ogistra', 'https://ogistra.rs', 'ogistra.ts'),
    (gen_random_uuid()::text, 'Oliva', 'https://oliva.rs', 'oliva.ts'),
    (gen_random_uuid()::text, 'Pansport', 'https://pansport.rs', 'pansport.ts'),
    (gen_random_uuid()::text, 'ProfFarm', 'https://proffarm.rs', 'profFarm.ts'),
    (gen_random_uuid()::text, 'Protein Box', 'https://proteinbox.rs', 'proteinbox.ts'),
    (gen_random_uuid()::text, 'Proteini', 'https://proteini.rs', 'proteini.ts'),
    (gen_random_uuid()::text, 'Ring Sport', 'https://ringsport.rs', 'ringSport.ts'),
    (gen_random_uuid()::text, 'Shopmania', 'https://shopmania.rs', 'shopmania.ts'),
    (gen_random_uuid()::text, 'SOP', 'https://sop.rs', 'sop.ts'),
    (gen_random_uuid()::text, 'Spartan Suplementi', 'https://spartansuplementi.rs', 'spartanSuplementi.ts'),
    (gen_random_uuid()::text, 'Srbotrade', 'https://srbotrade.rs', 'srbotrade.ts'),
    (gen_random_uuid()::text, 'Superior', 'https://superior.rs', 'superior.ts'),
    (gen_random_uuid()::text, 'Suplementi Shop', 'https://suplementishop.rs', 'suplementiShop.ts'),
    (gen_random_uuid()::text, 'Suplementi Srbija', 'https://suplementisrbija.rs', 'suplementiSrbija.ts'),
    (gen_random_uuid()::text, 'Supplement Shop', 'https://supplementshop.rs', 'supplementShop.ts'),
    (gen_random_uuid()::text, 'Supplement Store', 'https://supplementstore.rs', 'supplementStore.ts'),
    (gen_random_uuid()::text, 'Supplements', 'https://supplements.rs', 'supplements.ts'),
    (gen_random_uuid()::text, 'Titanium Sport', 'https://titaniumsport.rs', 'titaniumSport.ts'),
    (gen_random_uuid()::text, 'Vitalikum', 'https://vitalikum.rs', 'vitalikum.ts'),
    (gen_random_uuid()::text, 'Vitamin Shop', 'https://vitaminshop.rs', 'vitaminShop.ts'),
    (gen_random_uuid()::text, 'Web Apoteka', 'https://webapoteka.rs', 'webApoteka.ts'),
    (gen_random_uuid()::text, 'X Sport', 'https://xsport.rs', 'xSport.ts'),
    (gen_random_uuid()::text, 'XL Sport', 'https://xlsport.rs', 'xlSport.ts'),
    (gen_random_uuid()::text, 'Zelena Apoteka', 'https://zelenaapoteka.rs', 'zelenaApoteka.ts'),
    (gen_random_uuid()::text, 'Zero', 'https://zero.rs', 'zero.ts')
ON CONFLICT (name) DO NOTHING;
