services:
  # db:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: pharma_db
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  #   ports:
  #     - "5432:5432"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

  backend:
    build: ./go-backend
    ports:
      - "8080:8080"
      - "50051:50051"  # gRPC port
    environment:
      DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:5432/pharmagician
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      CONTACT_EMAIL: ${CONTACT_EMAIL}
      MEILI_URL: http://host.docker.internal:7700
      MEILI_API_KEY: ${MEILI_API_KEY}
    # depends_on:
    #   db:
    #     condition: service_healthy
    volumes:
      - ./go-backend:/app
    working_dir: /app
    command: ./pharma-server

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NEXT_PUBLIC_API_URL: http://localhost:8080
  #   depends_on:
  #     - backend
# volumes:
#   postgres_data:
