// @generated by protobuf-ts 2.11.1 with parameter client_grpc1
// @generated from protobuf file "service.proto" (package "service", syntax proto3)
// tslint:disable
import { PharmaAPI } from "./service";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { ProcessingAnalysisRequest } from "./service";
import type { RebuildIndexRequest } from "./service";
import type { ReprocessAllRequest } from "./service";
import type { ProcessRequest } from "./service";
import type { ContactRequest } from "./service";
import type { PriceComparisonRequest } from "./service";
import type { FacetsRequest } from "./service";
import type { SearchGroupsRequest } from "./service";
import type { GenericJsonResponse } from "./service";
import type { SearchRequest } from "./service";
import type { AutocompleteResponse } from "./service";
import type { AutocompleteRequest } from "./service";
import type { HealthResponse } from "./service";
import type { HealthRequest } from "./service";
import * as grpc from "@grpc/grpc-js";
/**
 * @generated from protobuf service service.PharmaAPI
 */
export interface IPharmaAPIClient {
    /**
     * @generated from protobuf rpc: Health
     */
    health(input: HealthRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: HealthResponse) => void): grpc.ClientUnaryCall;
    health(input: HealthRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: HealthResponse) => void): grpc.ClientUnaryCall;
    health(input: HealthRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: HealthResponse) => void): grpc.ClientUnaryCall;
    health(input: HealthRequest, callback: (err: grpc.ServiceError | null, value?: HealthResponse) => void): grpc.ClientUnaryCall;
    /**
     * @generated from protobuf rpc: Autocomplete
     */
    autocomplete(input: AutocompleteRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: AutocompleteResponse) => void): grpc.ClientUnaryCall;
    autocomplete(input: AutocompleteRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: AutocompleteResponse) => void): grpc.ClientUnaryCall;
    autocomplete(input: AutocompleteRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: AutocompleteResponse) => void): grpc.ClientUnaryCall;
    autocomplete(input: AutocompleteRequest, callback: (err: grpc.ServiceError | null, value?: AutocompleteResponse) => void): grpc.ClientUnaryCall;
    /**
     * @generated from protobuf rpc: Search
     */
    search(input: SearchRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    search(input: SearchRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    search(input: SearchRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    search(input: SearchRequest, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    /**
     * @generated from protobuf rpc: SearchGroups
     */
    searchGroups(input: SearchGroupsRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    searchGroups(input: SearchGroupsRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    searchGroups(input: SearchGroupsRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    searchGroups(input: SearchGroupsRequest, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    /**
     * @generated from protobuf rpc: GetFacets
     */
    getFacets(input: FacetsRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    getFacets(input: FacetsRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    getFacets(input: FacetsRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    getFacets(input: FacetsRequest, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    /**
     * @generated from protobuf rpc: PriceComparison
     */
    priceComparison(input: PriceComparisonRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    priceComparison(input: PriceComparisonRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    priceComparison(input: PriceComparisonRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    priceComparison(input: PriceComparisonRequest, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    /**
     * @generated from protobuf rpc: Contact
     */
    contact(input: ContactRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    contact(input: ContactRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    contact(input: ContactRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    contact(input: ContactRequest, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    /**
     * @generated from protobuf rpc: ProcessProducts
     */
    processProducts(input: ProcessRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    processProducts(input: ProcessRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    processProducts(input: ProcessRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    processProducts(input: ProcessRequest, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    /**
     * @generated from protobuf rpc: ReprocessAll
     */
    reprocessAll(input: ReprocessAllRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    reprocessAll(input: ReprocessAllRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    reprocessAll(input: ReprocessAllRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    reprocessAll(input: ReprocessAllRequest, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    /**
     * @generated from protobuf rpc: RebuildIndex
     */
    rebuildIndex(input: RebuildIndexRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    rebuildIndex(input: RebuildIndexRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    rebuildIndex(input: RebuildIndexRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    rebuildIndex(input: RebuildIndexRequest, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    /**
     * @generated from protobuf rpc: ProcessingAnalysis
     */
    processingAnalysis(input: ProcessingAnalysisRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    processingAnalysis(input: ProcessingAnalysisRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    processingAnalysis(input: ProcessingAnalysisRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
    processingAnalysis(input: ProcessingAnalysisRequest, callback: (err: grpc.ServiceError | null, value?: GenericJsonResponse) => void): grpc.ClientUnaryCall;
}
/**
 * @generated from protobuf service service.PharmaAPI
 */
export class PharmaAPIClient extends grpc.Client implements IPharmaAPIClient {
    private readonly _binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions>;
    constructor(address: string, credentials: grpc.ChannelCredentials, options: grpc.ClientOptions = {}, binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions> = {}) {
        super(address, credentials, options);
        this._binaryOptions = binaryOptions;
    }
    /**
     * @generated from protobuf rpc: Health
     */
    health(input: HealthRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: HealthResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: HealthResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: HealthResponse) => void)): grpc.ClientUnaryCall {
        const method = PharmaAPI.methods[0];
        return this.makeUnaryRequest<HealthRequest, HealthResponse>(`/${PharmaAPI.typeName}/${method.name}`, (value: HealthRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): HealthResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * @generated from protobuf rpc: Autocomplete
     */
    autocomplete(input: AutocompleteRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: AutocompleteResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: AutocompleteResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: AutocompleteResponse) => void)): grpc.ClientUnaryCall {
        const method = PharmaAPI.methods[1];
        return this.makeUnaryRequest<AutocompleteRequest, AutocompleteResponse>(`/${PharmaAPI.typeName}/${method.name}`, (value: AutocompleteRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): AutocompleteResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * @generated from protobuf rpc: Search
     */
    search(input: SearchRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void)): grpc.ClientUnaryCall {
        const method = PharmaAPI.methods[2];
        return this.makeUnaryRequest<SearchRequest, GenericJsonResponse>(`/${PharmaAPI.typeName}/${method.name}`, (value: SearchRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): GenericJsonResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * @generated from protobuf rpc: SearchGroups
     */
    searchGroups(input: SearchGroupsRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void)): grpc.ClientUnaryCall {
        const method = PharmaAPI.methods[3];
        return this.makeUnaryRequest<SearchGroupsRequest, GenericJsonResponse>(`/${PharmaAPI.typeName}/${method.name}`, (value: SearchGroupsRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): GenericJsonResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * @generated from protobuf rpc: GetFacets
     */
    getFacets(input: FacetsRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void)): grpc.ClientUnaryCall {
        const method = PharmaAPI.methods[4];
        return this.makeUnaryRequest<FacetsRequest, GenericJsonResponse>(`/${PharmaAPI.typeName}/${method.name}`, (value: FacetsRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): GenericJsonResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * @generated from protobuf rpc: PriceComparison
     */
    priceComparison(input: PriceComparisonRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void)): grpc.ClientUnaryCall {
        const method = PharmaAPI.methods[5];
        return this.makeUnaryRequest<PriceComparisonRequest, GenericJsonResponse>(`/${PharmaAPI.typeName}/${method.name}`, (value: PriceComparisonRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): GenericJsonResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * @generated from protobuf rpc: Contact
     */
    contact(input: ContactRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void)): grpc.ClientUnaryCall {
        const method = PharmaAPI.methods[6];
        return this.makeUnaryRequest<ContactRequest, GenericJsonResponse>(`/${PharmaAPI.typeName}/${method.name}`, (value: ContactRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): GenericJsonResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * @generated from protobuf rpc: ProcessProducts
     */
    processProducts(input: ProcessRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void)): grpc.ClientUnaryCall {
        const method = PharmaAPI.methods[7];
        return this.makeUnaryRequest<ProcessRequest, GenericJsonResponse>(`/${PharmaAPI.typeName}/${method.name}`, (value: ProcessRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): GenericJsonResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * @generated from protobuf rpc: ReprocessAll
     */
    reprocessAll(input: ReprocessAllRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void)): grpc.ClientUnaryCall {
        const method = PharmaAPI.methods[8];
        return this.makeUnaryRequest<ReprocessAllRequest, GenericJsonResponse>(`/${PharmaAPI.typeName}/${method.name}`, (value: ReprocessAllRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): GenericJsonResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * @generated from protobuf rpc: RebuildIndex
     */
    rebuildIndex(input: RebuildIndexRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void)): grpc.ClientUnaryCall {
        const method = PharmaAPI.methods[9];
        return this.makeUnaryRequest<RebuildIndexRequest, GenericJsonResponse>(`/${PharmaAPI.typeName}/${method.name}`, (value: RebuildIndexRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): GenericJsonResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * @generated from protobuf rpc: ProcessingAnalysis
     */
    processingAnalysis(input: ProcessingAnalysisRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: GenericJsonResponse) => void)): grpc.ClientUnaryCall {
        const method = PharmaAPI.methods[10];
        return this.makeUnaryRequest<ProcessingAnalysisRequest, GenericJsonResponse>(`/${PharmaAPI.typeName}/${method.name}`, (value: ProcessingAnalysisRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): GenericJsonResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
}
