// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: proto/service.proto

package service

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenericJsonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Struct       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericJsonResponse) Reset() {
	*x = GenericJsonResponse{}
	mi := &file_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericJsonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericJsonResponse) ProtoMessage() {}

func (x *GenericJsonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericJsonResponse.ProtoReflect.Descriptor instead.
func (*GenericJsonResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *GenericJsonResponse) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{1}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AutocompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutocompleteRequest) Reset() {
	*x = AutocompleteRequest{}
	mi := &file_proto_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutocompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutocompleteRequest) ProtoMessage() {}

func (x *AutocompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutocompleteRequest.ProtoReflect.Descriptor instead.
func (*AutocompleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *AutocompleteRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *AutocompleteRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AutocompleteSuggestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	VendorName    string                 `protobuf:"bytes,4,opt,name=vendor_name,json=vendorName,proto3" json:"vendor_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutocompleteSuggestion) Reset() {
	*x = AutocompleteSuggestion{}
	mi := &file_proto_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutocompleteSuggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutocompleteSuggestion) ProtoMessage() {}

func (x *AutocompleteSuggestion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutocompleteSuggestion.ProtoReflect.Descriptor instead.
func (*AutocompleteSuggestion) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *AutocompleteSuggestion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AutocompleteSuggestion) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AutocompleteSuggestion) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AutocompleteSuggestion) GetVendorName() string {
	if x != nil {
		return x.VendorName
	}
	return ""
}

type AutocompleteResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Suggestions   []*AutocompleteSuggestion `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	Query         string                    `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                     `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutocompleteResponse) Reset() {
	*x = AutocompleteResponse{}
	mi := &file_proto_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutocompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutocompleteResponse) ProtoMessage() {}

func (x *AutocompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutocompleteResponse.ProtoReflect.Descriptor instead.
func (*AutocompleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{5}
}

func (x *AutocompleteResponse) GetSuggestions() []*AutocompleteSuggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *AutocompleteResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AutocompleteResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	MinPrice      float64                `protobuf:"fixed64,4,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      float64                `protobuf:"fixed64,5,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	BrandNames    []string               `protobuf:"bytes,6,rep,name=brand_names,json=brandNames,proto3" json:"brand_names,omitempty"`
	Categories    []string               `protobuf:"bytes,7,rep,name=categories,proto3" json:"categories,omitempty"`
	Forms         []string               `protobuf:"bytes,8,rep,name=forms,proto3" json:"forms,omitempty"`
	InStockOnly   bool                   `protobuf:"varint,9,opt,name=in_stock_only,json=inStockOnly,proto3" json:"in_stock_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{6}
}

func (x *SearchRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchRequest) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *SearchRequest) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *SearchRequest) GetBrandNames() []string {
	if x != nil {
		return x.BrandNames
	}
	return nil
}

func (x *SearchRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *SearchRequest) GetForms() []string {
	if x != nil {
		return x.Forms
	}
	return nil
}

func (x *SearchRequest) GetInStockOnly() bool {
	if x != nil {
		return x.InStockOnly
	}
	return false
}

type SearchGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGroupsRequest) Reset() {
	*x = SearchGroupsRequest{}
	mi := &file_proto_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGroupsRequest) ProtoMessage() {}

func (x *SearchGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGroupsRequest.ProtoReflect.Descriptor instead.
func (*SearchGroupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{7}
}

func (x *SearchGroupsRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *SearchGroupsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FacetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FacetsRequest) Reset() {
	*x = FacetsRequest{}
	mi := &file_proto_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacetsRequest) ProtoMessage() {}

func (x *FacetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacetsRequest.ProtoReflect.Descriptor instead.
func (*FacetsRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{8}
}

type PriceComparisonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceComparisonRequest) Reset() {
	*x = PriceComparisonRequest{}
	mi := &file_proto_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceComparisonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceComparisonRequest) ProtoMessage() {}

func (x *PriceComparisonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceComparisonRequest.ProtoReflect.Descriptor instead.
func (*PriceComparisonRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{9}
}

func (x *PriceComparisonRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

type ContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactRequest) Reset() {
	*x = ContactRequest{}
	mi := &file_proto_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactRequest) ProtoMessage() {}

func (x *ContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactRequest.ProtoReflect.Descriptor instead.
func (*ContactRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{10}
}

func (x *ContactRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContactRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ContactRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchSize     int32                  `protobuf:"varint,1,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequest) Reset() {
	*x = ProcessRequest{}
	mi := &file_proto_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequest) ProtoMessage() {}

func (x *ProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{11}
}

func (x *ProcessRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type ReprocessAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReprocessAllRequest) Reset() {
	*x = ReprocessAllRequest{}
	mi := &file_proto_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReprocessAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReprocessAllRequest) ProtoMessage() {}

func (x *ReprocessAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReprocessAllRequest.ProtoReflect.Descriptor instead.
func (*ReprocessAllRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{12}
}

type RebuildIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebuildIndexRequest) Reset() {
	*x = RebuildIndexRequest{}
	mi := &file_proto_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildIndexRequest) ProtoMessage() {}

func (x *RebuildIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildIndexRequest.ProtoReflect.Descriptor instead.
func (*RebuildIndexRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{13}
}

type ProcessingAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessingAnalysisRequest) Reset() {
	*x = ProcessingAnalysisRequest{}
	mi := &file_proto_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingAnalysisRequest) ProtoMessage() {}

func (x *ProcessingAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingAnalysisRequest.ProtoReflect.Descriptor instead.
func (*ProcessingAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{14}
}

var File_proto_service_proto protoreflect.FileDescriptor

const file_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x13proto/service.proto\x12\aservice\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"B\n" +
	"\x13GenericJsonResponse\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"9\n" +
	"\x13AutocompleteRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"u\n" +
	"\x16AutocompleteSuggestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1f\n" +
	"\vvendor_name\x18\x04 \x01(\tR\n" +
	"vendorName\"\x85\x01\n" +
	"\x14AutocompleteResponse\x12A\n" +
	"\vsuggestions\x18\x01 \x03(\v2\x1f.service.AutocompleteSuggestionR\vsuggestions\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x80\x02\n" +
	"\rSearchRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x1b\n" +
	"\tmin_price\x18\x04 \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x05 \x01(\x01R\bmaxPrice\x12\x1f\n" +
	"\vbrand_names\x18\x06 \x03(\tR\n" +
	"brandNames\x12\x1e\n" +
	"\n" +
	"categories\x18\a \x03(\tR\n" +
	"categories\x12\x14\n" +
	"\x05forms\x18\b \x03(\tR\x05forms\x12\"\n" +
	"\rin_stock_only\x18\t \x01(\bR\vinStockOnly\"9\n" +
	"\x13SearchGroupsRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x0f\n" +
	"\rFacetsRequest\"&\n" +
	"\x16PriceComparisonRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\"T\n" +
	"\x0eContactRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"/\n" +
	"\x0eProcessRequest\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x01 \x01(\x05R\tbatchSize\"\x15\n" +
	"\x13ReprocessAllRequest\"\x15\n" +
	"\x13RebuildIndexRequest\"\x1b\n" +
	"\x19ProcessingAnalysisRequest2\x97\t\n" +
	"\tPharmaAPI\x12Q\n" +
	"\x06Health\x12\x16.service.HealthRequest\x1a\x17.service.HealthResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/health\x12m\n" +
	"\fAutocomplete\x12\x1c.service.AutocompleteRequest\x1a\x1d.service.AutocompleteResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/api/autocomplete\x12Z\n" +
	"\x06Search\x12\x16.service.SearchRequest\x1a\x1c.service.GenericJsonResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/api/search\x12m\n" +
	"\fSearchGroups\x12\x1c.service.SearchGroupsRequest\x1a\x1c.service.GenericJsonResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/api/search-groups\x12]\n" +
	"\tGetFacets\x12\x16.service.FacetsRequest\x1a\x1c.service.GenericJsonResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/api/facets\x12v\n" +
	"\x0fPriceComparison\x12\x1f.service.PriceComparisonRequest\x1a\x1c.service.GenericJsonResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/api/price-comparison\x12`\n" +
	"\aContact\x12\x17.service.ContactRequest\x1a\x1c.service.GenericJsonResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/api/contact\x12e\n" +
	"\x0fProcessProducts\x12\x17.service.ProcessRequest\x1a\x1c.service.GenericJsonResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x13/api/v1/api/process\x12m\n" +
	"\fReprocessAll\x12\x1c.service.ReprocessAllRequest\x1a\x1c.service.GenericJsonResponse\"!\x82\xd3\xe4\x93\x02\x1b\"\x19/api/v1/api/reprocess-all\x12m\n" +
	"\fRebuildIndex\x12\x1c.service.RebuildIndexRequest\x1a\x1c.service.GenericJsonResponse\"!\x82\xd3\xe4\x93\x02\x1b\"\x19/api/v1/api/rebuild-index\x12\x7f\n" +
	"\x12ProcessingAnalysis\x12\".service.ProcessingAnalysisRequest\x1a\x1c.service.GenericJsonResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/api/processing-analysisB>Z<github.com/callmeahab/pharma-search/go-backend/proto;serviceb\x06proto3"

var (
	file_proto_service_proto_rawDescOnce sync.Once
	file_proto_service_proto_rawDescData []byte
)

func file_proto_service_proto_rawDescGZIP() []byte {
	file_proto_service_proto_rawDescOnce.Do(func() {
		file_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)))
	})
	return file_proto_service_proto_rawDescData
}

var file_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_service_proto_goTypes = []any{
	(*GenericJsonResponse)(nil),       // 0: service.GenericJsonResponse
	(*HealthRequest)(nil),             // 1: service.HealthRequest
	(*HealthResponse)(nil),            // 2: service.HealthResponse
	(*AutocompleteRequest)(nil),       // 3: service.AutocompleteRequest
	(*AutocompleteSuggestion)(nil),    // 4: service.AutocompleteSuggestion
	(*AutocompleteResponse)(nil),      // 5: service.AutocompleteResponse
	(*SearchRequest)(nil),             // 6: service.SearchRequest
	(*SearchGroupsRequest)(nil),       // 7: service.SearchGroupsRequest
	(*FacetsRequest)(nil),             // 8: service.FacetsRequest
	(*PriceComparisonRequest)(nil),    // 9: service.PriceComparisonRequest
	(*ContactRequest)(nil),            // 10: service.ContactRequest
	(*ProcessRequest)(nil),            // 11: service.ProcessRequest
	(*ReprocessAllRequest)(nil),       // 12: service.ReprocessAllRequest
	(*RebuildIndexRequest)(nil),       // 13: service.RebuildIndexRequest
	(*ProcessingAnalysisRequest)(nil), // 14: service.ProcessingAnalysisRequest
	(*structpb.Struct)(nil),           // 15: google.protobuf.Struct
}
var file_proto_service_proto_depIdxs = []int32{
	15, // 0: service.GenericJsonResponse.data:type_name -> google.protobuf.Struct
	4,  // 1: service.AutocompleteResponse.suggestions:type_name -> service.AutocompleteSuggestion
	1,  // 2: service.PharmaAPI.Health:input_type -> service.HealthRequest
	3,  // 3: service.PharmaAPI.Autocomplete:input_type -> service.AutocompleteRequest
	6,  // 4: service.PharmaAPI.Search:input_type -> service.SearchRequest
	7,  // 5: service.PharmaAPI.SearchGroups:input_type -> service.SearchGroupsRequest
	8,  // 6: service.PharmaAPI.GetFacets:input_type -> service.FacetsRequest
	9,  // 7: service.PharmaAPI.PriceComparison:input_type -> service.PriceComparisonRequest
	10, // 8: service.PharmaAPI.Contact:input_type -> service.ContactRequest
	11, // 9: service.PharmaAPI.ProcessProducts:input_type -> service.ProcessRequest
	12, // 10: service.PharmaAPI.ReprocessAll:input_type -> service.ReprocessAllRequest
	13, // 11: service.PharmaAPI.RebuildIndex:input_type -> service.RebuildIndexRequest
	14, // 12: service.PharmaAPI.ProcessingAnalysis:input_type -> service.ProcessingAnalysisRequest
	2,  // 13: service.PharmaAPI.Health:output_type -> service.HealthResponse
	5,  // 14: service.PharmaAPI.Autocomplete:output_type -> service.AutocompleteResponse
	0,  // 15: service.PharmaAPI.Search:output_type -> service.GenericJsonResponse
	0,  // 16: service.PharmaAPI.SearchGroups:output_type -> service.GenericJsonResponse
	0,  // 17: service.PharmaAPI.GetFacets:output_type -> service.GenericJsonResponse
	0,  // 18: service.PharmaAPI.PriceComparison:output_type -> service.GenericJsonResponse
	0,  // 19: service.PharmaAPI.Contact:output_type -> service.GenericJsonResponse
	0,  // 20: service.PharmaAPI.ProcessProducts:output_type -> service.GenericJsonResponse
	0,  // 21: service.PharmaAPI.ReprocessAll:output_type -> service.GenericJsonResponse
	0,  // 22: service.PharmaAPI.RebuildIndex:output_type -> service.GenericJsonResponse
	0,  // 23: service.PharmaAPI.ProcessingAnalysis:output_type -> service.GenericJsonResponse
	13, // [13:24] is the sub-list for method output_type
	2,  // [2:13] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_service_proto_init() }
func file_proto_service_proto_init() {
	if File_proto_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_proto_goTypes,
		DependencyIndexes: file_proto_service_proto_depIdxs,
		MessageInfos:      file_proto_service_proto_msgTypes,
	}.Build()
	File_proto_service_proto = out.File
	file_proto_service_proto_goTypes = nil
	file_proto_service_proto_depIdxs = nil
}
